"""gdgd

Revision ID: d0b1559af68b
Revises: a1bd90f1634a
Create Date: 2021-06-14 13:43:56.168383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b1559af68b'
down_revision = 'a1bd90f1634a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_pitch_category'), 'pitch', ['category'], unique=False)
    op.drop_constraint('pitch_category_id_fkey', 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitch_category_id_fkey', 'pitch', 'category', ['category_id'], ['id'])
    op.drop_index(op.f('ix_pitch_category'), table_name='pitch')
    op.drop_column('pitch', 'category')
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    # ### end Alembic commands ###
